/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Clear: typeof import('./src/components/ImageModifier/Dash/Clear.vue')['default']
    Dash: typeof import('./src/components/ImageModifier/Dash/index.vue')['default']
    Drawing: typeof import('./src/components/Drawing.vue')['default']
    Existing: typeof import('./src/components/ImageModifier/Dash/Existing.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageModifier: typeof import('./src/components/ImageModifier/index.vue')['default']
    InsertImage: typeof import('./src/components/ImageModifier/Dash/InsertImage.vue')['default']
    LabelIconButton: typeof import('./src/components/LabelIconButton/index.vue')['default']
    Pencil: typeof import('./src/components/ImageModifier/Dash/Pencil.vue')['default']
    Rectangle: typeof import('./src/components/ImageModifier/Dash/Rectangle.vue')['default']
  }
}
